feat: Graphics card driver pre installation processing
Description: 显卡驱动预装处理

Log: 1. 在安装器启动前做显卡预装处理。
     2. 在安装器安装时做真实系统显卡预装处理。

Task: https://pms.uniontech.com/task-view-128907.html
Change-Id: I8131fa4b0312d019c99db3b578af8731c5327186

diff --git a/src/app/deepin-installer-both b/src/app/deepin-installer-both
--- a/src/app/deepin-installer-both
+++ b/src/app/deepin-installer-both
@@ -21,6 +21,45 @@ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
 auto_install_mode=0
 
+cd_rom() {
+    if [ -d /lib/live/mount/medium/live ]; then
+        CDROM=/lib/live/mount/medium
+    else
+        CDROM=/run/live/medium
+    fi
+    echo ${CDROM}
+}
+# 添加本地仓库，为英伟达显卡安装驱动所用
+setup_repo_sources() {
+    # 本地仓库的路径
+    local LIVE_DIR=$(cd_rom)
+    local LOC_REPO_PATH=$LIVE_DIR/dists
+
+    # add cdrom to sources.list
+    if [ -d $LOC_REPO_PATH ]; then
+        # commented source.list to let apt-get just using cdrom repo.
+        sed -i 's/^/#/g' /etc/apt/sources.list
+
+        dir=$(find  $LOC_REPO_PATH -name "Release" | xargs awk -F '[ :]+' '/Codename/{print $2}')
+        for name in $dir; do
+            # ident the cdrom first.
+            echo "deb [trusted=yes] file:$LIVE_DIR ${name} main" >> /etc/apt/sources.list
+        done
+
+        apt-get update || true
+    else
+        echo "$LOC_REPO_PATH is not a debian repository. Skipped." >> /var/log/deepin-installer-init.log
+    fi
+}
+
+deepin_nvidia_installer() {
+    if [ -f /usr/sbin/deepin-nvidia-installer ]; then
+        setup_repo_sources
+        deepin-nvidia-installer 0 || echo "run deepin-nvidia-installer 0 error"
+    else
+        echo "/usr/sbin/deepin-nvidia-installer is not found"
+    fi
+}
 parse_cmdline() {
   for x in $(cat /proc/cmdline); do
     case $x in
@@ -42,6 +81,8 @@ if [ x"$cli_mode" = xtrue ]; then
     chvt 2
     systemctl restart deepin-installer-cli
 else
+    # 启动前英伟达显卡驱动设置
+    deepin_nvidia_installer >> /var/log/deepin-installer-init.log 2>&1
     if [ $auto_install_mode -eq 1 ]; then
        /usr/lib/live/config/1081-deepin-auto-install
     else
